parameters:
  apiservice:
    apiservice_image: "apiservice:latest"
  webfrontend:
    webfrontend_image: "webfrontend:latest"
secrets:
  cache:
    REDIS_PASSWORD: ""
config:
  apiservice:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: "8080"
  webfrontend:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: "8080"
    services__apiservice__http__0: "http://apiservice-service:8080"
    services__apiservice__https__0: "https://apiservice-service:8080"
