---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "apiservice-config"
  labels:
    app.kubernetes.io/name: "aspiredemo"
    app.kubernetes.io/component: "apiservice"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.apiservice.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.apiservice.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.apiservice.HTTP_PORTS }}"
