---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "apiservice-deployment"
  labels:
    app.kubernetes.io/name: "aspiredemo"
    app.kubernetes.io/component: "apiservice"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "aspiredemo"
        app.kubernetes.io/component: "apiservice"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.apiservice.apiservice_image }}"
          name: "apiservice"
          envFrom:
            - configMapRef:
                name: "apiservice-config"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 8080
            - name: "https"
              protocol: "TCP"
              containerPort: 8080
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "aspiredemo"
      app.kubernetes.io/component: "apiservice"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
